debug = false

logLevel = "INFO"
defaultEntryPoints = ["http"]

[accessLog]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  
[entryPoints.traefik]
  address = ":8000"

[api]
entryPoint = "traefik"
dashboard = true

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
#domain = "docker.localhost"
watch = true
exposedByDefault = false

